#import <PEGKit/PKParser.h>

enum {
    XP_TOKEN_KIND_STAR = 14,
    XP_TOKEN_KIND_PLUS,
    XP_TOKEN_KIND_GE,
    XP_TOKEN_KIND_FALSE,
    XP_TOKEN_KIND_OR,
    XP_TOKEN_KIND_LT,
    XP_TOKEN_KIND_LE,
    XP_TOKEN_KIND_MINUS,
    XP_TOKEN_KIND_EQUALS,
    XP_TOKEN_KIND_PERCENT,
    XP_TOKEN_KIND_TRUE,
    XP_TOKEN_KIND_GT,
    XP_TOKEN_KIND_FORWARD_SLASH,
    XP_TOKEN_KIND_AND,
    XP_TOKEN_KIND_OPEN_PAREN,
    XP_TOKEN_KIND_YES_UPPER,
    XP_TOKEN_KIND_CLOSE_PAREN,
    XP_TOKEN_KIND_NE,
    XP_TOKEN_KIND_NO_UPPER,
};

@interface XPParser : PKParser

@end

