#import <PEGKit/PKParser.h>

enum {
    XP_TOKEN_KIND_GE = 14,
    XP_TOKEN_KIND_MINUS,
    XP_TOKEN_KIND_GE_SYM,
    XP_TOKEN_KIND_DOUBLE_AMPERSAND,
    XP_TOKEN_KIND_TRUE,
    XP_TOKEN_KIND_LT_SYM,
    XP_TOKEN_KIND_NOT_EQUAL,
    XP_TOKEN_KIND_FORWARD_SLASH,
    XP_TOKEN_KIND_EQUALS,
    XP_TOKEN_KIND_YES_UPPER,
    XP_TOKEN_KIND_OR,
    XP_TOKEN_KIND_GT_SYM,
    XP_TOKEN_KIND_NE,
    XP_TOKEN_KIND_LE_SYM,
    XP_TOKEN_KIND_AND,
    XP_TOKEN_KIND_PERCENT,
    XP_TOKEN_KIND_LT,
    XP_TOKEN_KIND_FALSE,
    XP_TOKEN_KIND_LE,
    XP_TOKEN_KIND_OPEN_PAREN,
    XP_TOKEN_KIND_DOUBLE_EQUALS,
    XP_TOKEN_KIND_EQ,
    XP_TOKEN_KIND_GT,
    XP_TOKEN_KIND_CLOSE_PAREN,
    XP_TOKEN_KIND_STAR,
    XP_TOKEN_KIND_NO_UPPER,
    XP_TOKEN_KIND_PLUS,
    XP_TOKEN_KIND_DOUBLE_PIPE,
};

@interface XPParser : PKParser

@end

